# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

dist: bionic
language: minimal
go:
  - 1.15.x
env:
  - GO111MODULE=on

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.25.1
  - sudo apt-get install -y shellcheck
  - sudo apt-get install -y pylint

script:
  - ./run_ci_build.sh
