# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

dist: bionic
language: go
go:
  - 1.15.5

env:
  - GO111MODULE=on

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.32.0
  - go mod download
  - sudo apt-get install -y shellcheck
  - sudo apt-get install -y pylint

script:
  - bash ./run_ci_build.sh
