# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

dist: bionic
language: minimal

before_install:
  - wget https://golang.org/dl/go1.15.5.linux-amd64.tar.gz
  - sudo tar -C /usr/local -xzf go1.15.5.linux-amd64.tar.gz
  - export $GOPATH=/usr/local/bin
  - export PATH=$PATH:$GOPATH/bin
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.25.1
  - sudo apt-get install -y shellcheck
  - sudo apt-get install -y pylint

script:
  - ./run_ci_build.sh
