# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

ProjectName: project_smtc
ClusterProvider: smartcity-cluster-provider
ClusterEdge: edge01
ClusterCloud: cloud01
ClusterLogicEdge: lc-edge01
ClusterLogicCloud: lc-cloud01
AdminCloud: default
CompositeApp: composite_smtc
AppEdge: smtc_edge
AppCloud: smtc_cloud
KubeConfigEdge: /opt/clusters_config/edgecluster_config
KubeConfigCloud: /opt/clusters_config/cloudcluster_config
EdgeClusterLabel: LabelSmartCityEdge
CloudClusterLabel: LabelSmartCityCloud
HelmEdgeApp: /opt/smtc_edge_helmchart.tar.gz
HelmCloudApp: /opt/smtc_cloud_helmchart.tar.gz
ProfileEdgeAppName: smtc_edge-profile
ProfileCloudAppName: smtc_cloud-profile
ProfileEdgeApp: /opt/smtc_edge_profile.tar.gz
ProfileCloudApp:  /opt/smtc_cloud_profile.tar.gz
DeploymentIntent: smtc-deployment-intent-group
CompositeProfile: smtc_composite-profile
GenericPlacementIntent: smtc-placement-intent
AppEdgePlacementIntent: smtcedge-placement-intent
AppCloudPlacementIntent: smtccloud-placement-intent
GenericK8sIntent: smtc-k8s-intent
SmtcEdgeResources: smtcSensorConfig-edge-resources
SmtcCloudResources: smtcSensorConfig-cloud-resources
ResourceName: sensor-info
SmtcEdgeCustomizations: smtcSensorConfig-edge-customizations
SmtcCloudCustomizations: smtcSensorConfig-cloud-customizations
ConfigMapFile: /opt/sensor-info.json
RsyncIP: <EMCO_IP>
RsyncPort: 31595
GacIP: <EMCO_IP>
GacPort: 31554
